### ISSUE TITLE
Not show fee on summary total

### ISSUE THREAD

**Issue by mrkhoa99** [sivajik34/Delivery-Signature-Magento2#1]
Your question here: http://magento.stackexchange.com/questions/125000/checkout-page-refresh-issue/126916#126916

**Comment by mrkhoa99** [comment]
Hello @sivajik34 

I checked your code, seem that the logic of fee calculation is not correct. How you calculate the fee? Using Plugin, Observer or anything else?

**Comment by sivajik34** [comment]
Please look at Kensium/DeliverySign/Plugin/Checkout/Model/ShippingInformationManagement.php
